### ISSUE TITLE
AssertionError: Parameter 'ste0_conv0_weight' is missing in file 

### ISSUE THREAD

**Issue by abxyz888** [HCIILAB/Scene-Text-Removal#24]
environment:
Python 2.7.12
mxnet-cu80 == 1.3.1
matplotlib 2.2.5

I use the pretrain models to Testing and I met this problems. 
But I can't fix this error. Could anybody hep me? 

root@2f99ac26d9b7:/workspace# python test.py --test_image=./test/image/img_58.jpg --model=./root/.mxnet/models/vgg16-e660d456.params --result=./output/
Traceback (most recent call last):
  File "test.py", line 81, in <module>
    test(args)
  File "test.py", line 30, in test
    netG, netD,net, net_label ,trainerG, trainerD, trainerV, trainerL = set_network(args)
  File "/workspace/network.py", line 79, in set_network
    netG.collect_params().load(args.model,ctx = ctx)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/gluon/parameter.py", line 911, in load
    name[lprefix:], filename, _brief_print_list(arg_dict.keys()))
AssertionError: Parameter 'ste0_conv0_weight' is missing in file './root/.mxnet/models/vgg16-e660d456.params', which contains parameters: 'features.24.weight', 'features.17.bias', 'features.21.weight', ..., 'features.17.weight', 'features.14.bias', 'features.33.weight', 'features.10.bias'. Please make sure source and target networks have the same prefix.

**Comment by codexyd123** [comment]
I also encountered the same problem

**Comment by AItechnology** [comment]
I got same error

**Comment by arnavmehta7** [comment]
Samee!
